<x-layout>
  @if (config('festival.avslutad'))
    @include('partials.tack.nav')
    @include('partials.tack.hero')
    @include('partials.ticker', ['text' => config('festival.tack.ticker')])
    @include('partials.tack.artister')
    @include('partials.tack.medverkande')
    @include('partials.tack.sponsorer')
    @include('partials.footer')
  @else
    @include('partials.nav')
    @include('partials.hero')
    @include('partials.ticker')
    @include('partials.video')
    @include('partials.forelasning')
    @include('partials.artister')
    @include('partials.program')
    @include('partials.biljetter')
    @include('shirts._form')
    @include('partials.hitta')
    @include('partials.faq')
    @include('partials.sponsorer')
    @include('partials.footer')
  @endif
</x-layout>
